server:
  port: 8880
spring:
  profiles:
    active: test
  datasource: #数据库链接相关配置
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${DATABASE}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
#    druid:
#      db-type: com.alibaba.druid.pool.DruidDataSource
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      testWhileIdle: true
#      testOnBorrow: true
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1
#      filter: wall,stat,log4j
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 5000
#    jedis.pool:
#      max-active: 50
#      max-wait: 3000
#      max-idle: 20
#      min-idle: 2

# noinspection SpringBootApplicationYaml
actable:
  table:
    auto: update
  model:
    pack: com.wuyou.robot.entity
  database:
    type: mysql
mybatis-plus:
  #  mapper-locations: classpath*:**/*.xml
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

logging:
  level:
    ROOT: INFO
    love.forte: DEBUG
    com.wuyou.robot: DEBUG

